### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished

### ISSUE THREAD

**Issue by paroliav** [mgsnova/feature#20]
Hi,

I'm getting the error with ActiveRecord, I don't use ActiveRecord in my application.
Is there any way to disable ActiveRecord in features gem?

Failure/Error: Unable to find matching line from backtrace
ActiveRecord::ConnectionNotEstablished:
ActiveRecord::ConnectionNotEstablished

**Comment by mgsnova** [comment]
Are you still getting such an error with the latest version?

**Comment by mgsnova** [comment]
I close this issue, because I got no more feedback about the details of the problem
