### ISSUE TITLE
Ability to access a list of all features

### ISSUE THREAD

**Issue by krsyoung** [mgsnova/feature#36]
It would be very helpful in my application if I could get a list of all of the current features and their respective values for debugging purposes.

It looks like it might just be a matter of exposing `@active_features` but was curious if there might be a reason to not do this?

Maybe something as simple as: `Feature.active_features` that returns the hash of feature to value.

Will submit a pull request if this sounds reasonable.  love this library.

**Comment by mgsnova** [comment]
See #37
